name: GitHub Actions Práctica
on:
  push:
    branches:
      - main

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar el flujo de trabajo
        run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"

      - name: Mostrar información del entorno
        run: echo "El trabajo se está ejecutando en un servidor ${runner.os} hospedado en GitHub"

      - name: Mostrar información del repositorio
        run: echo "El nombre de la rama es: ${github.ref} y tu repositorio es: ${github.repository}"

      - name: Verificar el código del repositorio
        run: |
          echo "El repositorio: ${github.repository} ha sido clonado al runner."
          echo "El flujo de trabajo está listo para verificar el código en el runner."

      - name: Listar archivos en el repositorio
        run: ls ${{ github.workspace }}
